console.log(0 === 0);   // true (strict equality)
console.log(0 == 0);    // true (loose equality)   
console.log(0 == "0");    // true (loose equality)  
console.log(0 === "0");   // false (strict equality)
console.log("" == 0);  // true (loose equality)
console.log("" == "0");  // false (loose equality)

console.log(0 == false);  // true (loose equality)
console.log(null == 0); // false (loose equality)
console.log(null == undefined); // true (loose equality)
console.log(null === undefined); // false (strict equality)